Reuse Panoptes User and Project IDs for Subscriber and List IDs
zooniverse/listmonk-sync pull request #4
Opened 2024-04-12 17:44 UTC by Tooyosi

Solves for this ticket: https://github.com/zooniverse/listmonk-sync/issues/3

2024-04-12 20:05 UTC, zwolf approved these changes
Couple quick comments but looks good. Did this get tested against the new staging database?

2024-04-12 20:05 UTC, zwolf commented on panoptes.rb
> +        'id' => generate_id(index),
This is worth adding a short comment to explain why you have to generate your own ID here.

2024-04-12 20:05 UTC, zwolf commented on panoptes.rb
> +    new_id = 9000 + (index + offset)
9000 would be enough for now but I'd throw an extra 0 on there just to get a full order of magnitude away from the real ones.

2024-04-12 21:59 UTC, lcjohnso commented on listmonk.rb
> +          l['project_id'],
Following my suggestion in panoptes.project_lists, the reference should be to `id` here rather than `project_id`
```suggestion
          l['id'],
```

2024-04-15 11:19 UTC, Tooyosi commented
@lcjohnso so the main reason i added the `project_id` logic is cos od the possibility of duplicates in the `project_lists` method.  The `project_emailable_users` can sometimes have a user show up multiple times but for different projects and when using just the `id`, it'll trow a unique key violation. Another way i thought of was to assign id to be project_id i.e `'id' => h['project_id']` just in the `project_lists`.

2024-04-15 14:55 UTC, lcjohnso commented
@zwolf Can you comment on how deduplication of the subscribers list is supposed to work?  Based on Zach's comment in  [L74](https://github.com/zooniverse/listmonk-sync/blob/main/panoptes.rb#L74), it seems like duplicates (or the need for deduplication) was existing.

2024-04-15 20:03 UTC, zwolf requested changes
Yeah maybe I got confused reading this too but the deduplicating of users is intentional as a user can be subscribed to multiple projects but needs to be inserted as a subscriber only once. Nothing about how users are pulled needs to change except for including the id in the select statement, this id becomes the user's subscriber ID on insert.

I agree with Cliff's suggestions. I didn't read this carefully enough while assuming that it was being tested on the new staging instance. I'll want to check the new staging data before this merges, since that will affect all syncs afterward.

2024-04-16 10:28 UTC, Tooyosi commented
I think i have more clarity now, i made an update using the project_id on only the project_lists (matches the suggestions by @lcjohnso  )

2024-04-18 15:44 UTC, zwolf approved these changes

2024-04-18 15:44 UTC, merged